trigger:
  branches:
    include:
      - main
  tags:
    include:
      - v*

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  solution: 'ExcelValidator.sln'
  configuration: 'Release'

steps:

- task: UseDotNet@2
  displayName: Install .NET 8 SDK
  inputs:
    packageType: sdk
    version: '8.0.x'

- script: |
    dotnet --info
    dotnet nuget list source
  displayName: Environment Information

- script: |
    dotnet restore $(solution) --verbosity detailed
  displayName: Restore

- script: |
    dotnet build $(solution) \
      --configuration $(configuration) \
      --no-restore
  displayName: Build

- script: |
    dotnet test \
      --configuration $(configuration) \
      --no-build \
      --collect:"XPlat Code Coverage"
  displayName: Test

- script: |
    dotnet pack ExcelValidator/ExcelValidator.csproj \
      --configuration $(configuration) \
      --no-build \
      --output $(Build.ArtifactStagingDirectory)
  displayName: Pack

- publish: $(Build.ArtifactStagingDirectory)
  artifact: nupkg

- script: |
    dotnet nuget push "$(Build.ArtifactStagingDirectory)/*.nupkg" \
      --api-key $(APIKEY) \
      --source https://api.nuget.org/v3/index.json \
      --skip-duplicate
  displayName: Push to NuGet
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))